function market = marketMaker(mo, marketRootId, marketBranchId, marketMin, marketMax, traderId)
% Create test market with dummy +s signature

pms = mo.getPreviousMarketSig;

market =  struct('marketRootId', marketRootId, 'marketBranchId', marketBranchId,...
                               'marketMin', marketMin, 'marketMax', marketMax,...
                               'traderId', traderId, 'previousSig', pms,...
                               'signatureMsg', pms,...
                               'signature', [pms{1}, 's']);